//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCOURSE.Model.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QLCOURSE.Model.Helper.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da Ton Tai!.
        /// </summary>
        public static string DaTonTai {
            get {
                return ResourceManager.GetString("DaTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia Chi:.
        /// </summary>
        public static string DiaChi {
            get {
                return ResourceManager.GetString("DiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co loi khi nhap lieu, hay thu lai!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi Chu:.
        /// </summary>
        public static string GhiChu {
            get {
                return ResourceManager.GetString("GhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoc Phi:.
        /// </summary>
        public static string HocPhi {
            get {
                return ResourceManager.GetString("HocPhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho Ten:.
        /// </summary>
        public static string HoTen {
            get {
                return ResourceManager.GetString("HoTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoa Hoc ID:.
        /// </summary>
        public static string KhoaHocID {
            get {
                return ResourceManager.GetString("KhoaHocID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong Ton Tai!.
        /// </summary>
        public static string KhongTonTai {
            get {
                return ResourceManager.GetString("KhongTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap Mo Ta:.
        /// </summary>
        public static string MoTa {
            get {
                return ResourceManager.GetString("MoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngay Bat Dau:.
        /// </summary>
        public static string NgayBatDau {
            get {
                return ResourceManager.GetString("NgayBatDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngay Ket Thuc: .
        /// </summary>
        public static string NgayKetThuc {
            get {
                return ResourceManager.GetString("NgayKetThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngay Sinh:.
        /// </summary>
        public static string NgaySinh {
            get {
                return ResourceManager.GetString("NgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noi Dung:.
        /// </summary>
        public static string NoiDung {
            get {
                return ResourceManager.GetString("NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que Quan:.
        /// </summary>
        public static string QueQuan {
            get {
                return ResourceManager.GetString("QueQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So Dien Thoai:.
        /// </summary>
        public static string SoDienThoai {
            get {
                return ResourceManager.GetString("SoDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap Ten Khoa Hoc:.
        /// </summary>
        public static string TenKhoaHoc {
            get {
                return ResourceManager.GetString("TenKhoaHoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tac thanh cong!.
        /// </summary>
        public static string ThanhCong {
            get {
                return ResourceManager.GetString("ThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tac that bai!.
        /// </summary>
        public static string ThatBai {
            get {
                return ResourceManager.GetString("ThatBai", resourceCulture);
            }
        }
    }
}
